= Introduction

Goals of the IR. Automatization/abstraction of tedious tasks when dealing with GPU APIs: pipeline configuration, resource bindings, etc. Lots of boilerplate, error-prone, often need to keep things in sync manually between shader and main program.
Useful for early-stage exploration, when the graphics pipeline is not clear yet: need to quickly explore different strategies for using the GPU, but massive amount of boilerplate greatly increases iteration times and developer dissatisfaction.


== Goals

. *Abstract away resource binding and API boilerplate*
. *Remove boilerplate in shaders*
** Make it easy to do program transformations on the IR rather than on an AST
. *Reduce iteration times by making more things editable at runtime*
** like an effect system
. *Things that affect the rendering should be closer together in the code*
** don't want to go into application code to change the blending state for the shader I'm editing: it should be next to the shader, or even better, in the shader code.
. *I don't want to deal with shader permutations for different kinds of geometry  (static objects, skinned objects, deformations, subdivision surfaces...)*
** Geometry processing and fragment shading should be separate concerns
** I should be able to mix-and-match different geometry types with different materials without having to handle a ton of #defines in code
. *I want it to be able to generate optimized submission plans for complex scenes*
** E.g. minimize state transitions, descriptor changes
** A bit unclear for now

== Architecture

Programs are divided into packages, of which there are two kinds:
- source package, where the user provides the source code, which is then parsed
- declaration packages, for which there are no sources, and the user (by that I mean, the developer of the application) provides definitions directly

Source packages are parsed to ASTs. ASTs are then typechecked, producing a typed-AST (TAST). Bodies of declarations are typechecked on demand. Finally, the TAST of a package and its dependencies can be lowered to HIR, which is basically an in-memory representation of SPIR-V.


=== HIR flow

The resulting HIR is not yet a shader module. Parameters and the I/O interface may not have explicit binding numbers, there might be refs to external declarations, and the HIR may have multiple entry points.

* Linking: to provide a definition for external decls
* Interface layout specification: the layout of the shader interface is specified: individual uniform params are mapped to UBO fields
& set/binding numbers are assigned
** the app provides the layout of the data made available to the shader
** in return, the app can reflect the shader params that have not been mapped to anything
